#include "structure/S4/CompositionEncapsulation.h"
#include <QCoreApplication>
#include <iostream>
namespace { bool check(bool v,const char* n){if(!v)std::cerr<<"FAIL ["<<n<<"]\n";else std::cout<<"PASS ["<<n<<"]\n";return v;}
S1::Configuration s1(){S1::Configuration c;c.rootId="project";c.responsibilities.append({"project","project","Project",S1::ResponsibilityKind::Project,{},{},{},{},{}});c.responsibilities.append({"host","host","Host",S1::ResponsibilityKind::Feature,{},{},{},{},{}});c.responsibilities.append({"child","child","Child",S1::ResponsibilityKind::Feature,{},{},{},{},{}});c.responsibilities.append({"nested","nested","Nested",S1::ResponsibilityKind::Feature,{},{},{},{},{}});c.artifacts.append({"private-child","child/private","source","child",S1::OwnershipMode::Exclusive,{},{},false,{},{},{},{},{}});return c;}
S2::Configuration s2(){S2::Configuration c;c.rootId="root";c.nodes.append({"root","root","Project",{},{},"project",{},"root",{}});c.boundaries.append({"child-boundary","child","src/child","EXCLUSIVE",{},{},{},{},false,{}});return c;}
S3::Configuration s3(){S3::Configuration c;c.interfaces.append({"child-api","child-api","Child API","child",S3::InterfaceVisibility::Public,S3::InterfaceKind::Api,{},{},"",{}});c.interfaces.append({"child-private","child-private","Child private","child",S3::InterfaceVisibility::Private,S3::InterfaceKind::Api,{},{},"",{}});return c;}
S4::Configuration valid(){S4::Configuration c;c.compositionContracts.append({"host-child","host-child","Host Child","host","child",{}, {},S4::CompositionKind::Hosts,{S4::HostOperation::Mount,S4::HostOperation::Resize,S4::HostOperation::Show,S4::HostOperation::Hide,S4::HostOperation::ConnectPublicContract},{"child-api"},S4::ChildIsolationMode::ContractOnly,S4::Multiplicity::Single,{}, {}});c.encapsulationPolicies.append({"child-policy","child-policy","Child Policy","child",{"host-child"},true,{"child-api"},{S4::HostOperation::Mount,S4::HostOperation::Resize,S4::HostOperation::Show,S4::HostOperation::Hide},{"private-child"},"MOUNTED",{}});return c;}}
int main(int argc,char**argv){QCoreApplication app(argc,argv);bool all=true;const auto a=s1();const auto b=s2();const auto d=s3();auto c=valid();QString e;auto r=S4::audit(c,a,b,d);all&=check(r.valid,"valid composition audits");all&=check(S4::toJson(c)==S4::toJson(c),"deterministic S4 serialization");S4::Configuration round;all&=check(S4::fromJson(S4::toJson(c),&round,&e)&&S4::toJson(round)==S4::toJson(c),"S4 persistence round trip");all&=check(c.lifecycle.identifier()=="S4.1.0.0.0","default S4 lifecycle");ProcessVersionState st=ProcessVersionState::empty();st.hasNextStructure=true;st.nextStructure=c.lifecycle;all&=check(ProcessVersionLifecycle::startNextStructure(&st,&e)&&st.activeStructure.identifier()=="S4.1.1.0.0","S4 lifecycle start");all&=check(ProcessVersionLifecycle::certifyCurrentStructureIteration(&st,&e)&&st.activeStructure.identifier()=="S4.1.1.1.0","S4 lifecycle certification");all&=check(ProcessVersionLifecycle::completeActiveStructure(&st,&e)&&st.structureHistory.last().identifier()=="S4.1.1.1.1","S4 lifecycle completion");auto bad=c;bad.compositionContracts[0].allowedInterfaceIds={"child-private"};all&=check(!S4::audit(bad,a,b,d).valid,"private S3 interface cannot be composition surface");bad=c;bad.observations.append({"private-observation","host","child",S4::HostOperation::Resize,"child-api",{},"evidence","obs",{},"OBSERVED",{{"directPrivateAccess",true}}});all&=check(!S4::audit(bad,a,b,d).valid,"private child access diagnosed");bad=c;bad.observations.append({"undeclared","host","child",S4::HostOperation::Focus,"child-api",{},"evidence","obs",{},"OBSERVED",{}});auto ar=S4::audit(bad,a,b,d);bool found=false;for(const auto&x:ar.diagnostics)found|=x.ruleCode.contains("UNDECLARED");all&=check(found,"undeclared operation diagnosed");bad=c;bad.compositionContracts.append(c.compositionContracts.first());all&=check(!S4::audit(bad,a,b,d).valid,"duplicate composition rejected");std::cout<<(all?"S4 tests PASS\n":"S4 tests FAIL\n");return all?0:1;}
