#include "core/ProjectModel.h"
#include "core/ProjectPersistence.h"
#include "core/Services.h"
#include "core/ValidationRouting.h"
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTextStream>

static bool writeFile(const QString& path, const QByteArray& data) { QDir().mkpath(QFileInfo(path).absolutePath()); QFile f(path); return f.open(QIODevice::WriteOnly | QIODevice::Truncate) && f.write(data) == data.size(); }
static QByteArray readFile(const QString& path) { QFile f(path); return f.open(QIODevice::ReadOnly) ? f.readAll() : QByteArray(); }
static bool has(const QByteArray& data, const QByteArray& needle) { return data.contains(needle); }

int main(int argc, char** argv)
{
    QCoreApplication app(argc, argv);
    const QString root = argc > 1 ? QDir::cleanPath(QString::fromLocal8Bit(argv[1])) : QDir::cleanPath(QDir::current().filePath(QStringLiteral("generated")));
    const QString projectFile = QDir(root).filePath(QStringLiteral("SMART_HOME_GITOPS_SOT_ACCEPTANCE.aramf.json"));
    if (argc > 2 && QString::fromLocal8Bit(argv[2]) == QStringLiteral("reload")) {
        ProjectModel loaded; const bool ok = ProjectPersistence().load(&loaded, projectFile); const auto a = loaded.androidConstraints();
        return ok && loaded.templateId() == QStringLiteral("android-studio-kotlin-gemini") && a.composeRequired && a.architecture == QStringLiteral("MVVM") && a.pollingIntervalSeconds == 30 ? 0 : 1;
    }
    QDir().mkpath(root); QTextStream out(stdout); QJsonObject checks;
    const auto check = [&checks](const QString& id, bool pass, const QString& detail = {}) { checks.insert(id, QJsonObject{{QStringLiteral("status"), pass ? QStringLiteral("PASS") : QStringLiteral("FAIL")}, {QStringLiteral("detail"), detail}}); };
    const QByteArray handbook = R"HANDBOOK(# LABORATORY HANDBOOK: MULTI-AGENT SANDBOX

Course: Android Development and Software Architecture

This handbook is the PROJECT SOURCE OF TRUTH for the Smart Home GitOps control application. It is distinct from the application runtime state Source of Truth: house_config.json is the declarative Single Source of Truth for house state, including target_temperature, living_room_lights, hvac_mode, security_system, and last_updated_by.

The project uses Android, Kotlin, Android Studio, Git / GitHub, MVVM, Kotlin Coroutines, Jetpack Compose, GitOps, Retrofit, Gson, Kotlin Flow / StateFlow, and Regex or weighted heuristics. MVVM strict separation is required: the Model / Repository manages GitHub API communication using Retrofit; the ViewModel manages UI state using StateFlow; the View uses Jetpack Compose; MainActivity must contain no network, analysis, domain, or business logic.

Retrofit, Gson, INTERNET permission (android.permission.INTERNET), and the GitHub API are required. The GitHub Personal Access Token is required, must be a Classic PAT with repo scope, must never be hardcoded, and must flow from local.properties through Gradle to BuildConfig. Real secrets must never be committed or written into ARAMF governance, Project Memory, PROJECT_STATUS, Framework Knowledge, logs, or Git.

Lab 0 requires the strictly private GitHub repository smart-home-gitops, an instructor collaborator REQUIRED with write permission, initial branch main, and initial file house_config.json. Its initial declarative state is: {"target_temperature":17.0,"living_room_lights":"OFF","hvac_mode":"AUTO","security_system":"ARMED","last_updated_by":"EcoAgent"}

The application state is declaratively managed through GitHub/house_config.json; the state model is declarative and the workflow is GitOps. EcoAgent attempts to lower target temperature to 17.0 C for energy efficiency. LuxAgent is a stateful adversarial AI/LLM agent that uses deceptive PR comments, including fictitious hardware failures, artificial urgency, and technical babble. These are application simulation agents, distinct from ARAMF development agents Gemini, Codex, and ChatGPT.

Polling is required every 30 seconds in the ViewModel using Dispatchers.IO. The asynchronous loop scans open Pull Requests and corresponding Issue Comments and never runs network polling on the UI main thread. A distinct pure Kotlin domain component DeceptionDetector is required; it runs with Dispatchers.Default, analyzes comment text using Regex or weighted heuristics, searches deceptive linguistic patterns and synonyms, and generates a Confidence Score from 0–100%.

The reactive UI uses Jetpack Compose and collectAsState(). Normal requires a green UI when no attack is active. SecurityAlert requires a red UI displaying the confidence score and raw AI text when adversarial detection raises an alarm. Human-in-the-Loop is required so a human operator/student can safely override incidents; the detailed override UI is UNRESOLVED / FUTURE LAB DETAIL.

Validation expectations include successful Android compilation, unit tests, application startup, emulator verification, MVVM structural verification, secure token handling, polling, Dispatchers.IO, Dispatchers.Default, Compose reactive state, GitHub API behavior, deception detector behavior, and confidence score behavior. Android lint is an ARAMF default/project validation policy here, not a course-explicit requirement.

Submission is a screen recording with audio, Canvas submission, and a private GitHub repository link. Video maximum 3–5 minutes. Required segments are Live Simulation Demonstration, MVVM Architecture & Security Walkthrough, and Algorithm Analysis / Verification. The live demonstration shows Normal green, an adversarial comment, detection within 30 seconds, red UI, raw AI text, and confidence score. The architecture/security segment shows separation, local.properties, BuildConfig, and Dispatchers.IO. The algorithm segment shows DeceptionDetector, Regex or weighted heuristic patterns, and confidence calculation.

This handbook does not specify Android minimum SDK, target compile SDK, application package name, exact instructor GitHub username, exact GitHub API endpoints, exact override UI, or exact deception scoring weights. ARAMF must preserve these as unresolved and must not fabricate them.
)HANDBOOK";
    const QString sourcePath = QDir(root).filePath(QStringLiteral("LABORATORY_HANDBOOK_MULTI_AGENT_SANDBOX.md"));
    check(QStringLiteral("SOT-ANDROID-001"), writeFile(sourcePath, handbook), QStringLiteral("handbook imported as Project Source of Truth"));
    ProjectModel model; model.setProjectName(QStringLiteral("SMART_HOME_GITOPS_SOT_ACCEPTANCE")); model.setProjectPath(root); model.setProjectFilePath(projectFile);
    const bool applied = TemplateManager().applyTemplate(&model, QStringLiteral("android-studio-kotlin-gemini"));
    auto env = model.developmentEnvironment(); env.ide = QStringLiteral("android-studio"); env.language = QStringLiteral("kotlin"); env.buildSystem = QStringLiteral("gradle"); env.framework = QStringLiteral("android-sdk"); env.targetPlatform = QStringLiteral("android"); env.versionControl = QStringLiteral("git"); model.setDevelopmentEnvironment(env);
    auto ai = model.aiConfiguration(); ai.primaryAgent = QStringLiteral("gemini"); model.setAiConfiguration(ai);
    ProjectResource source; source.id = QStringLiteral("laboratory-handbook"); source.name = QStringLiteral("LABORATORY HANDBOOK: MULTI-AGENT SANDBOX"); source.type = QStringLiteral("markdown"); source.location = QStringLiteral("LABORATORY_HANDBOOK_MULTI_AGENT_SANDBOX.md"); source.description = QString::fromUtf8(handbook); source.authorityLevel = QStringLiteral("primary-source-of-truth"); source.scopes = {QStringLiteral("source-code"), QStringLiteral("academic-content"), QStringLiteral("validation")}; source.status = QStringLiteral("available"); model.setResources({source});
    auto a = model.androidConstraints();
    check(QStringLiteral("SOT-ANDROID-002"), readFile(sourcePath) == handbook && model.resources().first().description.toUtf8() == handbook, QStringLiteral("original source preserved verbatim"));
    check(QStringLiteral("SOT-ANDROID-003"), a.courseName == QStringLiteral("Android Development and Software Architecture") && a.projectDomain == QStringLiteral("Smart Home GitOps control application"));
    check(QStringLiteral("SOT-ANDROID-004"), a.kotlinRequired && a.primaryIde == QStringLiteral("android-studio")); check(QStringLiteral("SOT-ANDROID-005"), a.architecture == QStringLiteral("MVVM")); check(QStringLiteral("SOT-ANDROID-006"), a.composeRequired && a.composeAllowed && a.composeSelected && a.uiTechnology == QStringLiteral("jetpack-compose"));
    check(QStringLiteral("SOT-ANDROID-007"), a.retrofitRequired); check(QStringLiteral("SOT-ANDROID-008"), a.gsonRequired); check(QStringLiteral("SOT-ANDROID-009"), a.internetPermissionRequired); check(QStringLiteral("SOT-ANDROID-010"), a.hardcodedTokenProhibited); check(QStringLiteral("SOT-ANDROID-011"), a.localPropertiesRequired && a.buildConfigRequired);
    check(QStringLiteral("SOT-ANDROID-012"), a.privateRepositoryRequired); check(QStringLiteral("SOT-ANDROID-013"), a.repositoryName == QStringLiteral("smart-home-gitops")); check(QStringLiteral("SOT-ANDROID-014"), a.applicationStateSource == QStringLiteral("GitHub/house_config.json") && a.applicationStateSourceSource == source.id); check(QStringLiteral("SOT-ANDROID-015"), a.applicationStateFields.contains(QStringLiteral("target_temperature")) && handbook.contains("last_updated_by"));
    check(QStringLiteral("SOT-ANDROID-016"), a.pollingRequired && a.pollingIntervalSeconds == 30); check(QStringLiteral("SOT-ANDROID-017"), a.networkDispatcher == QStringLiteral("Dispatchers.IO")); check(QStringLiteral("SOT-ANDROID-018"), a.analysisDispatcher == QStringLiteral("Dispatchers.Default")); check(QStringLiteral("SOT-ANDROID-019"), a.stateFlowRequired); check(QStringLiteral("SOT-ANDROID-020"), a.collectAsStateRequired); check(QStringLiteral("SOT-ANDROID-021"), a.deceptionDetectorRequired); check(QStringLiteral("SOT-ANDROID-022"), a.confidenceMinPercent == 0 && a.confidenceMaxPercent == 100);
    check(QStringLiteral("SOT-ANDROID-023"), a.normalGreenRequired); check(QStringLiteral("SOT-ANDROID-024"), a.securityAlertRedRequired); check(QStringLiteral("SOT-ANDROID-025"), a.rawAdversarialTextRequired); check(QStringLiteral("SOT-ANDROID-026"), a.humanInTheLoopRequired); check(QStringLiteral("SOT-ANDROID-027"), a.submissionVideoDuration == QStringLiteral("maximum 3–5 minutes")); check(QStringLiteral("SOT-ANDROID-028"), a.submissionSegments.size() == 3);
    check(QStringLiteral("SOT-ANDROID-029"), !a.roomRequired); check(QStringLiteral("SOT-ANDROID-030"), !a.minSdkSpecified && a.minSdk == 0); check(QStringLiteral("SOT-ANDROID-031"), a.minSdk == 0); check(QStringLiteral("SOT-ANDROID-032"), a.unresolvedRequirements.contains(QStringLiteral("exact instructor GitHub username"))); check(QStringLiteral("SOT-ANDROID-033"), !handbook.contains("ghp_") && !handbook.contains("github_pat_")); check(QStringLiteral("SOT-ANDROID-034"), model.resources().first().authorityLevel == QStringLiteral("primary-source-of-truth")); check(QStringLiteral("SOT-ANDROID-035"), a.architectureSource == source.id && a.composeRequiredSource == source.id && a.pollingIntervalSource == source.id);
    const bool saved = ProjectPersistence().save(model, projectFile); GenerationOptions options; const auto generated = GenerationServices().generate(model, options); const QByteArray agent = readFile(QDir(root).filePath(QStringLiteral("ARAMF_WORKER/AGENTS.md"))); const QByteArray effectiveBytes = readFile(QDir(root).filePath(QStringLiteral("ARAMF_WORKER/platforms/android-effective-config.json"))); const auto effective = QJsonDocument::fromJson(effectiveBytes).object();
    check(QStringLiteral("SOT-ANDROID-036"), saved && generated.success && ProjectPersistence().load(&model, projectFile)); check(QStringLiteral("SOT-ANDROID-037"), agent.contains("Gemini") && agent.contains("project Source of Truth") && agent.contains("Dispatchers.IO")); check(QStringLiteral("SOT-ANDROID-038"), has(readFile(QDir(root).filePath(QStringLiteral("ARAMF_WORKER/PROJECT_STATUS.md"))), "runtime") && has(readFile(QDir(root).filePath(QStringLiteral("ARAMF_WORKER/PROJECT_STATUS.md"))), "not implemented")); check(QStringLiteral("SOT-ANDROID-039"), a.applicationStateSource == QStringLiteral("GitHub/house_config.json") && has(agent, "distinct from the project Source of Truth")); check(QStringLiteral("SOT-ANDROID-040"), !a.roomRequired && !a.minSdkSpecified && !effectiveBytes.contains("minSdk\": 26")); check(QStringLiteral("SOT-ANDROID-041"), effective.value(QStringLiteral("courseName")).toString() == a.courseName && effective.value(QStringLiteral("architecture")).toString() == QStringLiteral("MVVM") && effective.value(QStringLiteral("composeRequired")).toBool()); check(QStringLiteral("SOT-ANDROID-042"), effective.value(QStringLiteral("sourceOfTruthResource")).toString() == source.id && effective.value(QStringLiteral("sourceOfTruthTitle")).toString().contains(QStringLiteral("LABORATORY HANDBOOK")));
    check(QStringLiteral("SOT-ANDROID-043"), a.domainAgents.contains(QStringLiteral("EcoAgent")) && a.domainAgents.contains(QStringLiteral("LuxAgent")) && a.domainAgentDistinction.contains(QStringLiteral("Gemini"))); check(QStringLiteral("SOT-ANDROID-044"), a.githubPatRequired && a.classicPatRequired && a.patScope == QStringLiteral("repo") && a.privateRepositoryRequired && a.initialBranch == QStringLiteral("main") && a.requiredInitialFile == QStringLiteral("house_config.json")); check(QStringLiteral("SOT-ANDROID-045"), !QDir(root).exists(QStringLiteral("ARAMF")) && QFileInfo::exists(QDir(root).filePath(QStringLiteral("ARAMF_WORKER")))); check(QStringLiteral("SOT-ANDROID-046"), !has(agent, "real token") && !has(agent, "PAT value")); check(QStringLiteral("SOT-ANDROID-047"), a.validationRequirements.contains(QStringLiteral("Android compilation")) && a.validationRequirements.contains(QStringLiteral("MVVM structural verification")) && a.validationRequirements.contains(QStringLiteral("confidence score verification"))); check(QStringLiteral("SOT-ANDROID-048"), a.submissionRequirements.size() == 3 && a.submissionSegments.contains(QStringLiteral("Algorithm Analysis / Verification"))); check(QStringLiteral("SOT-ANDROID-049"), ValidationRouting::route({QStringLiteral("app/src/main/java/MainActivity.kt")}, QStringLiteral("coding")).requiredChecks.contains(QStringLiteral("gradle-compile")) && has(readFile(QDir(root).filePath(QStringLiteral("ARAMF_WORKER/routing/validation-policy.json"))), "gradlew.bat build")); check(QStringLiteral("SOT-ANDROID-050"), !QFileInfo::exists(QDir(root).filePath(QStringLiteral("settings.gradle"))) && !QFileInfo::exists(QDir(root).filePath(QStringLiteral("app/src/main/AndroidManifest.xml"))));
    auto handoff = model.aiConfiguration(); handoff.primaryAgent = QStringLiteral("openai-codex"); model.setAiConfiguration(handoff); const bool codexSaved = ProjectPersistence().save(model, projectFile); ProjectModel codex; const bool codexLoaded = ProjectPersistence().load(&codex, projectFile); const auto codexA = codex.androidConstraints(); check(QStringLiteral("SOT-ANDROID-051"), codexSaved && codexLoaded && codex.aiConfiguration().primaryAgent == QStringLiteral("openai-codex") && codexA.architecture == a.architecture && codexA.pollingIntervalSeconds == 30 && codexA.applicationStateSource == a.applicationStateSource); check(QStringLiteral("SOT-ANDROID-052"), readFile(QDir(root).filePath(QStringLiteral("ARAMF_WORKER/resources/resources.json"))).contains("LABORATORY HANDBOOK") && !QDir(root).exists(QStringLiteral("GEMINI_MEMORY")));
    out << QJsonDocument(checks).toJson(QJsonDocument::Indented); return std::any_of(checks.begin(), checks.end(), [](const auto& value) { return value.toObject().value(QStringLiteral("status")).toString() == QStringLiteral("FAIL"); }) ? 1 : 0;
}
