#include "DevelopmentEnvironmentPage.h"
#include <QComboBox>
#include <QCheckBox>
#include <QGroupBox>
#include <QFormLayout>
#include <QLabel>
#include <QSignalBlocker>
#include <QVBoxLayout>
static QComboBox* combo(QWidget*p,std::initializer_list<std::pair<const char*,const char*>> values){auto*c=new QComboBox(p);for(auto&v:values)c->addItem(v.first,v.second);return c;}
DevelopmentEnvironmentPage::DevelopmentEnvironmentPage(ProjectModel*m,QWidget*p):QWidget(p),model_(m){auto*l=new QVBoxLayout(this);l->addWidget(new QLabel(tr("<h2>Development Environment</h2>Select compatible tools, targets and build capabilities."),this));auto*f=new QFormLayout;ide_=combo(this,{{"Visual Studio Code","vscode"},{"Qt Creator","qt-creator"},{"CLion","clion"}});compiler_=combo(this,{{"MSYS2 UCRT64 GCC","msys2-ucrt64-gcc"},{"Clang","clang"},{"MSVC","msvc"},{"Python runtime","python"}});os_=combo(this,{{"Windows","windows"},{"Linux","linux"},{"macOS","macos"}});target_=combo(this,{{"Desktop","desktop"},{"Web","web"},{"Server","server"},{"Embedded","embedded"},{"Cloud","cloud"}});build_=combo(this,{{"CMake","cmake"},{"Ninja","ninja"},{"npm scripts","npm"},{"Make","make"},{"PyProject","pyproject"}});f->addRow(tr("IDE"),ide_);f->addRow(tr("Primary compiler/runtime"),compiler_);f->addRow(tr("Operating system"),os_);f->addRow(tr("Primary target"),target_);f->addRow(tr("Build system"),build_);l->addLayout(f);auto*multi=new QGroupBox(tr("Additional targets and capabilities"),this);auto*multiLayout=new QVBoxLayout(multi);for(const auto&text:{tr("Cross-platform build"),tr("Debug build"),tr("Release build"),tr("Package installer"),tr("Container image"),tr("Cross-compilation")})multiLayout->addWidget(new QCheckBox(text,multi));l->addWidget(multi);l->addStretch();auto update=[this]{auto e=model_->developmentEnvironment();e.ide=ide_->currentData().toString();e.compiler=compiler_->currentData().toString();e.operatingSystem=os_->currentData().toString();e.targetPlatform=target_->currentData().toString();e.buildSystem=build_->currentData().toString();model_->setDevelopmentEnvironment(e);};connect(ide_,&QComboBox::currentIndexChanged, this, update);connect(compiler_,&QComboBox::currentIndexChanged,this,update);connect(os_,&QComboBox::currentIndexChanged,this,update);connect(target_,&QComboBox::currentIndexChanged,this,update);connect(build_,&QComboBox::currentIndexChanged,this,update);connect(model_,&ProjectModel::developmentEnvironmentChanged,this,&DevelopmentEnvironmentPage::refreshFromModel);refreshFromModel();}
void DevelopmentEnvironmentPage::refreshFromModel(){const auto e=model_->developmentEnvironment();const QSignalBlocker a(ide_),b(compiler_),c(os_),d(target_),f(build_);ide_->setCurrentIndex(ide_->findData(e.ide));compiler_->setCurrentIndex(compiler_->findData(e.compiler));os_->setCurrentIndex(os_->findData(e.operatingSystem));target_->setCurrentIndex(target_->findData(e.targetPlatform));build_->setCurrentIndex(build_->findData(e.buildSystem));}
