#include "ProjectProfilePage.h"
#include <QCheckBox>
#include <QFormLayout>
#include <QGroupBox>
#include <QLabel>
#include <QScrollArea>
#include <QSignalBlocker>
#include <QVBoxLayout>
ProjectProfilePage::ProjectProfilePage(ProjectModel* model,QWidget* parent):QWidget(parent),model_(model){auto*content=new QWidget;auto*layout=new QVBoxLayout(content);layout->addWidget(new QLabel(tr("<h1>Project Profile</h1><p>Select every capability that belongs to the project. Combinations are intentional: Python + React + SQLite is just as valid as C++ + Qt + PostgreSQL.</p>"),content));
    const QList<QPair<QString,QStringList>> groups{{tr("Project shape"),{tr("Backend / service|backend"),tr("Frontend / web UI|frontend"),tr("Desktop application|desktop"),tr("Embedded firmware|embedded"),tr("Reusable library|library"),tr("Research / thesis|research")}},{tr("Languages"),{tr("Python|python"),tr("C++|cpp"),tr("TypeScript / JavaScript|typescript"),tr("C# / .NET|dotnet"),tr("SQL|sql")}},{tr("Frameworks and UI"),{tr("Qt|qt"),tr("React|react"),tr("Express / Node.js|node"),tr("FastAPI / Flask / Django|python-web"),tr("ASP.NET|aspnet"),tr("Pico SDK|pico-sdk")}},{tr("Data and delivery"),{tr("SQLite|sqlite"),tr("PostgreSQL|postgres"),tr("REST API|rest"),tr("Desktop packaging|packaging"),tr("Docker / container|container"),tr("Microcontroller target|microcontroller")}},{tr("Quality and collaboration"),{tr("Unit testing|unit-test"),tr("Integration testing|integration-test"),tr("End-to-end testing|e2e-test"),tr("CI/CD|cicd"),tr("Documentation / thesis evidence|documentation"),tr("AI-assisted development|ai-assisted" )}}};
    for(const auto& definition:groups){auto*box=new QGroupBox(definition.first,content);auto*boxLayout=new QVBoxLayout(box);for(const auto& option:definition.second){const auto parts=option.split('|');auto*check=new QCheckBox(parts.value(0),box);check->setProperty("profileId",parts.value(1));check->setToolTip(tr("Include %1 in the project profile.").arg(parts.value(0)));boxLayout->addWidget(check);options_<<check;connect(check,&QCheckBox::toggled,this,[this]{QStringList selected;for(auto*item:options_)if(item->isChecked())selected<<item->property("profileId").toString();model_->setProfileSelections(selected);emit profileChanged(selected);});}layout->addWidget(box);}
    options_.value(0)->setChecked(true);options_.value(1)->setChecked(true);options_.value(6)->setChecked(true);options_.value(10)->setChecked(true);options_.value(20)->setChecked(true);model_->setProfileSelections({"backend","frontend","python","react","sqlite","packaging","unit-test","ai-assisted"});
    auto*explanation=new QLabel(tr("<b>Progressive disclosure</b><br>Only settings supported by the selected combination should appear in later pages. A project may have several backends, multiple targets, or both a desktop UI and a web UI."),content);explanation->setWordWrap(true);explanation->setStyleSheet("background:#eef5ff; padding:12px; border-radius:6px;");layout->addWidget(explanation);layout->addStretch();auto*scroll=new QScrollArea(this);scroll->setWidgetResizable(true);scroll->setFrameShape(QFrame::NoFrame);scroll->setWidget(content);auto*outer=new QVBoxLayout(this);outer->setContentsMargins(0,0,0,0);outer->addWidget(scroll);}
