#pragma once

enum class WorkflowPageId {
    Setup,
    Academic,
    Languages,
    Frameworks,
    DevelopmentTools,
    Platforms,
    HardwareArchitecture,
    BuildDelivery,
    AiAgents,
    AiResponsibilities,
    AiAutonomy,
    AiIntegration,
    ResourceInventory,
    ResourceAuthority,
    ResourcePolicy,
    RuleSelection,
    RuleRouting,
    MemoryCapture,
    MemoryMaintenance,
    Review,
    Generate,
    Verify,
    Finalize,
    UpdateReview,
    UpdateApply,
    ImprovementBacklog
};
