#include "StructuralEvolutionEnforcement.h"

#include <QCryptographicHash>
#include <QJsonArray>
#include <QJsonDocument>
#include <QSet>
#include <algorithm>
#include <tuple>

namespace S6 {
namespace {
const QStringList targets = {"NONE", "TASK_PREFLIGHT", "TASK_EXECUTION", "TASK_POSTFLIGHT", "BUILD", "TEST", "GENERATE", "VERIFY", "FINALIZE", "RELEASE"};
const QStringList severities = {"INFO", "WARNING", "ERROR", "BLOCKER"};
const QStringList operations = {"CREATE", "MOVE", "COPY", "RENAME", "UPDATE_REFERENCE", "ADD_INTERFACE", "REMOVE_REFERENCE", "SPLIT_RESPONSIBILITY", "ADOPT_PROPOSAL", "REWIRE_DEPENDENCY", "UPDATE_COMPOSITION", "REGENERATE", "VALIDATE"};

QJsonArray strings(QStringList values)
{
    std::sort(values.begin(), values.end()); QJsonArray result;
    for (const auto& value : values) result.append(value); return result;
}
QStringList stringList(const QJsonValue& value)
{
    QStringList result; for (const auto& value : value.toArray()) result.append(value.toString()); return result;
}
QString enumName(int value, const QStringList& names) { return value >= 0 && value < names.size() ? names.at(value) : QStringLiteral("UNKNOWN"); }
bool enumValue(const QString& value, const QStringList& names, int* result) { const int index=names.indexOf(value.trimmed().toUpper()); if(index<0||!result)return false;*result=index;return true; }
bool validTarget(const QString& target) { return targets.contains(target); }
bool validSeverity(const QString& value) { return severities.contains(value.toUpper()); }
int severityRank(const QString& value) { return severities.indexOf(value.toUpper()); }
QString hashObject(const QJsonObject& value) { return QString::fromLatin1(QCryptographicHash::hash(QJsonDocument(value).toJson(QJsonDocument::Compact), QCryptographicHash::Sha256).toHex()); }
QString hashBytes(const QByteArray& value) { return QString::fromLatin1(QCryptographicHash::hash(value, QCryptographicHash::Sha256).toHex()); }
void add(AuditResult* result, const Diagnostic& diagnostic) { result->diagnostics.append(diagnostic); if (diagnostic.severity=="ERROR" || diagnostic.severity=="BLOCKER") result->valid=false; }
void duplicate(const QString& id, const QString& rule, AuditResult* result) { add(result, {rule,"ERROR",{}, {},{}, {},{},QStringLiteral("Duplicate or missing stable ID: %1.").arg(id),"Provide a unique stable ID.","UNMAPPED"}); }
QString stable(const QString& seed, const QString& prefix) { return prefix + QStringLiteral("-") + hashBytes(seed.toUtf8()).left(24); }

QJsonObject policyJson(const EnforcementPolicy& p) { return {{"id",p.id},{"stableKey",p.stableKey},{"name",p.name},{"scopeResponsibilityId",p.scopeResponsibilityId},{"mode",modeName(p.mode)},{"maturity",maturityName(p.maturity)},{"enforcementTargets",strings(p.enforcementTargets)},{"defaultDisposition",dispositionName(p.defaultDisposition)},{"effectiveFrom",p.effectiveFrom},{"metadata",p.metadata}}; }
QJsonObject bindingJson(const RuleBinding& b) { return {{"id",b.id},{"stableKey",b.stableKey},{"sourceAuthority",b.sourceAuthority},{"sourceRuleCode",b.sourceRuleCode},{"policyId",b.policyId},{"minimumSeverity",b.minimumSeverity},{"disposition",dispositionName(b.disposition)},{"enforcementTargets",strings(b.enforcementTargets)},{"confidenceRequirement",b.confidenceRequirement},{"metadata",b.metadata}}; }
QJsonObject exemptionJson(const Exemption& e) { return {{"id",e.id},{"stableKey",e.stableKey},{"scopeResponsibilityId",e.scopeResponsibilityId},{"ruleCode",e.ruleCode},{"reason",e.reason},{"approvedBy",e.approvedBy},{"expiresAt",e.expiresAt},{"status",e.status},{"metadata",e.metadata}}; }
QJsonObject waiverJson(const Waiver& w) { return {{"id",w.id},{"stableKey",w.stableKey},{"findingFingerprint",w.findingFingerprint},{"reason",w.reason},{"approvedBy",w.approvedBy},{"validUntil",w.validUntil},{"status",w.status},{"metadata",w.metadata}}; }
QJsonObject operationJson(const MigrationOperation& o) { return {{"id",o.id},{"operation",o.operation},{"target",o.target},{"affectedArtifacts",strings(o.affectedArtifacts)},{"destructive",o.destructive},{"approvalState",approvalStateName(o.approvalState)},{"metadata",o.metadata}}; }
QJsonObject migrationJson(const MigrationPlan& p) { QJsonArray ops; for (auto operation:p.proposedOperations) ops.append(operationJson(operation)); return {{"id",p.id},{"stableKey",p.stableKey},{"sourceStateFingerprint",p.sourceStateFingerprint},{"targetStateDescription",p.targetStateDescription},{"affectedResponsibilities",strings(p.affectedResponsibilities)},{"affectedArtifacts",strings(p.affectedArtifacts)},{"proposedOperations",ops},{"approvalState",approvalStateName(p.approvalState)},{"executionState",p.executionState},{"rollbackState",rollbackStateName(p.rollbackState)},{"metadata",p.metadata}}; }
}

QString modeName(Mode value) { return enumName(static_cast<int>(value), {"AUDIT","WARN","ENFORCE"}); }
QString maturityName(Maturity value) { return enumName(static_cast<int>(value), {"EXPERIMENTAL","OBSERVE","WARN","ENFORCE"}); }
QString dispositionName(Disposition value) { return enumName(static_cast<int>(value), {"IGNORE","RECORD","WARN","REQUIRE_ACKNOWLEDGEMENT","BLOCK","REMEDIATE","MIGRATION_REQUIRED"}); }
QString approvalStateName(ApprovalState value) { return enumName(static_cast<int>(value), {"NOT_REQUIRED","REQUIRED","APPROVED","REJECTED"}); }
QString rollbackStateName(RollbackState value) { return enumName(static_cast<int>(value), {"NOT_REQUIRED","AVAILABLE","REQUIRED","EXECUTED","FAILED"}); }
bool modeFromName(const QString& value, Mode* result) { int i; bool ok=enumValue(value,{"AUDIT","WARN","ENFORCE"},&i);if(ok&&result)*result=static_cast<Mode>(i);return ok; }
bool maturityFromName(const QString& value, Maturity* result) { int i; bool ok=enumValue(value,{"EXPERIMENTAL","OBSERVE","WARN","ENFORCE"},&i);if(ok&&result)*result=static_cast<Maturity>(i);return ok; }
bool dispositionFromName(const QString& value, Disposition* result) { int i; bool ok=enumValue(value,{"IGNORE","RECORD","WARN","REQUIRE_ACKNOWLEDGEMENT","BLOCK","REMEDIATE","MIGRATION_REQUIRED"},&i);if(ok&&result)*result=static_cast<Disposition>(i);return ok; }
bool approvalStateFromName(const QString& value, ApprovalState* result) { int i; bool ok=enumValue(value,{"NOT_REQUIRED","REQUIRED","APPROVED","REJECTED"},&i);if(ok&&result)*result=static_cast<ApprovalState>(i);return ok; }
bool rollbackStateFromName(const QString& value, RollbackState* result) { int i; bool ok=enumValue(value,{"NOT_REQUIRED","AVAILABLE","REQUIRED","EXECUTED","FAILED"},&i);if(ok&&result)*result=static_cast<RollbackState>(i);return ok; }

QString findingFingerprint(const Finding& finding)
{
    if (!finding.findingFingerprint.isEmpty()) return finding.findingFingerprint;
    return hashObject({{"sourceAuthority",finding.sourceAuthority},{"sourceRuleCode",finding.sourceRuleCode},{"scopeResponsibilityId",finding.scopeResponsibilityId},{"severity",finding.severity},{"evidenceReference",finding.evidenceReference},{"metadata",finding.metadata}});
}

QJsonObject toJson(const Configuration& c)
{
    auto policies=c.enforcementPolicies; auto bindings=c.ruleBindings; auto exemptions=c.exemptions; auto waivers=c.waivers;
    auto remediations=c.remediationPlans; auto migrations=c.migrationPlans; auto observations=c.observations;
    std::sort(policies.begin(),policies.end(),[](const auto&a,const auto&b){return a.id<b.id;}); std::sort(bindings.begin(),bindings.end(),[](const auto&a,const auto&b){return a.id<b.id;}); std::sort(exemptions.begin(),exemptions.end(),[](const auto&a,const auto&b){return a.id<b.id;}); std::sort(waivers.begin(),waivers.end(),[](const auto&a,const auto&b){return a.id<b.id;}); std::sort(remediations.begin(),remediations.end(),[](const auto&a,const auto&b){return a.id<b.id;}); std::sort(migrations.begin(),migrations.end(),[](const auto&a,const auto&b){return a.id<b.id;}); std::sort(observations.begin(),observations.end(),[](const auto&a,const auto&b){return a.id<b.id;});
    QJsonArray p,b,e,w,r,m,o;
    for(const auto&x:policies)p.append(policyJson(x)); for(const auto&x:bindings)b.append(bindingJson(x)); for(const auto&x:exemptions)e.append(exemptionJson(x)); for(const auto&x:waivers)w.append(waiverJson(x));
    for(const auto&x:remediations)r.append(QJsonObject{{"id",x.id},{"stableKey",x.stableKey},{"findingReferences",strings(x.findingReferences)},{"proposedActions",strings(x.proposedActions)},{"requiresApproval",x.requiresApproval},{"status",x.status},{"metadata",x.metadata}});
    for(const auto&x:migrations)m.append(migrationJson(x)); for(const auto&x:observations)o.append(QJsonObject{{"id",x.id},{"findingFingerprint",x.findingFingerprint},{"status",x.status},{"evidenceReference",x.evidenceReference},{"metadata",x.metadata}});
    QJsonArray history;for(const auto&v:c.lifecycleHistory)history.append(processVersionToJson(v));
    return {{"schemaVersion",c.schemaVersion},{"enforcementPolicies",p},{"ruleBindings",b},{"exemptions",e},{"waivers",w},{"remediationPlans",r},{"migrationPlans",m},{"observations",o},{"lifecycle",processVersionToJson(c.lifecycle)},{"lifecycleHistory",history},{"metadata",c.metadata}};
}

bool fromJson(const QJsonValue& value, Configuration* out, QString* error)
{
    if(!out||!value.isObject()){if(error)*error="S6 configuration must be an object.";return false;} const auto root=value.toObject(); Configuration c; c.schemaVersion=root.value("schemaVersion").toInt(1);
    for(const auto&v:root.value("enforcementPolicies").toArray()){auto x=v.toObject();EnforcementPolicy p;p.id=x.value("id").toString();p.stableKey=x.value("stableKey").toString();p.name=x.value("name").toString();p.scopeResponsibilityId=x.value("scopeResponsibilityId").toString();if(!modeFromName(x.value("mode").toString("AUDIT"),&p.mode)||!maturityFromName(x.value("maturity").toString("OBSERVE"),&p.maturity)||!dispositionFromName(x.value("defaultDisposition").toString("RECORD"),&p.defaultDisposition)){if(error)*error="Invalid S6 policy enum.";return false;}p.enforcementTargets=stringList(x.value("enforcementTargets"));p.effectiveFrom=x.value("effectiveFrom").toString();p.metadata=x.value("metadata").toObject();c.enforcementPolicies.append(p);}
    for(const auto&v:root.value("ruleBindings").toArray()){auto x=v.toObject();RuleBinding b;b.id=x.value("id").toString();b.stableKey=x.value("stableKey").toString();b.sourceAuthority=x.value("sourceAuthority").toString();b.sourceRuleCode=x.value("sourceRuleCode").toString();b.policyId=x.value("policyId").toString();b.minimumSeverity=x.value("minimumSeverity").toString("INFO");if(!dispositionFromName(x.value("disposition").toString("RECORD"),&b.disposition)){if(error)*error="Invalid S6 binding disposition.";return false;}b.enforcementTargets=stringList(x.value("enforcementTargets"));b.confidenceRequirement=x.value("confidenceRequirement").toString();b.metadata=x.value("metadata").toObject();c.ruleBindings.append(b);}
    for(const auto&v:root.value("exemptions").toArray()){auto x=v.toObject();Exemption e;e.id=x.value("id").toString();e.stableKey=x.value("stableKey").toString();e.scopeResponsibilityId=x.value("scopeResponsibilityId").toString();e.ruleCode=x.value("ruleCode").toString();e.reason=x.value("reason").toString();e.approvedBy=x.value("approvedBy").toString();e.expiresAt=x.value("expiresAt").toString();e.status=x.value("status").toString("ACTIVE");e.metadata=x.value("metadata").toObject();c.exemptions.append(e);}
    for(const auto&v:root.value("waivers").toArray()){auto x=v.toObject();Waiver w;w.id=x.value("id").toString();w.stableKey=x.value("stableKey").toString();w.findingFingerprint=x.value("findingFingerprint").toString();w.reason=x.value("reason").toString();w.approvedBy=x.value("approvedBy").toString();w.validUntil=x.value("validUntil").toString();w.status=x.value("status").toString("ACTIVE");w.metadata=x.value("metadata").toObject();c.waivers.append(w);}
    for(const auto&v:root.value("remediationPlans").toArray()){auto x=v.toObject();RemediationPlan p;p.id=x.value("id").toString();p.stableKey=x.value("stableKey").toString();p.findingReferences=stringList(x.value("findingReferences"));p.proposedActions=stringList(x.value("proposedActions"));p.requiresApproval=x.value("requiresApproval").toBool(true);p.status=x.value("status").toString("PLANNED");p.metadata=x.value("metadata").toObject();c.remediationPlans.append(p);}
    for(const auto&v:root.value("migrationPlans").toArray()){auto x=v.toObject();MigrationPlan p;p.id=x.value("id").toString();p.stableKey=x.value("stableKey").toString();p.sourceStateFingerprint=x.value("sourceStateFingerprint").toString();p.targetStateDescription=x.value("targetStateDescription").toString();p.affectedResponsibilities=stringList(x.value("affectedResponsibilities"));p.affectedArtifacts=stringList(x.value("affectedArtifacts"));for(const auto&ov:x.value("proposedOperations").toArray()){auto q=ov.toObject();MigrationOperation o;o.id=q.value("id").toString();o.operation=q.value("operation").toString();o.target=q.value("target").toString();o.affectedArtifacts=stringList(q.value("affectedArtifacts"));o.destructive=q.value("destructive").toBool(false);if(!approvalStateFromName(q.value("approvalState").toString("REQUIRED"),&o.approvalState)){if(error)*error="Invalid S6 operation approval state.";return false;}o.metadata=q.value("metadata").toObject();p.proposedOperations.append(o);}if(!approvalStateFromName(x.value("approvalState").toString("REQUIRED"),&p.approvalState)||!rollbackStateFromName(x.value("rollbackState").toString("NOT_REQUIRED"),&p.rollbackState)){if(error)*error="Invalid S6 migration state.";return false;}p.executionState=x.value("executionState").toString("PLANNED");p.metadata=x.value("metadata").toObject();c.migrationPlans.append(p);}
    for(const auto&v:root.value("observations").toArray()){auto x=v.toObject();Observation o;o.id=x.value("id").toString();o.findingFingerprint=x.value("findingFingerprint").toString();o.status=x.value("status").toString();o.evidenceReference=x.value("evidenceReference").toString();o.metadata=x.value("metadata").toObject();c.observations.append(o);}
    if(root.contains("lifecycle")&&!processVersionFromJson(root.value("lifecycle"),&c.lifecycle,error))return false;for(const auto&v:root.value("lifecycleHistory").toArray()){ProcessVersion p;if(!processVersionFromJson(v,&p,error))return false;c.lifecycleHistory.append(p);}c.metadata=root.value("metadata").toObject();*out=c;return true;
}

AuditResult audit(const Configuration& c, const QStringList& knownAuthorities)
{
    AuditResult result; result.modelFingerprint=hashObject(toJson(c)); QSet<QString> ids; auto idCheck=[&](const QString&id,const QString&rule){if(id.isEmpty()||ids.contains(id))duplicate(id,rule,&result);ids.insert(id);};
    for(const auto&p:c.enforcementPolicies){idCheck(p.id,"S6.DUPLICATE_POLICY");for(const auto&t:p.enforcementTargets)if(!validTarget(t))add(&result,{"S6.INVALID_TARGET","ERROR",{}, {},p.id,{}, {},QStringLiteral("Unknown enforcement target: %1.").arg(t),"Use a canonical explicit enforcement target.","UNMAPPED"});if(p.mode==Mode::Enforce&&p.maturity!=Maturity::Enforce)add(&result,{"S6.ENFORCE_MATURITY_MISMATCH","ERROR",{}, {},p.id,{}, {},"ENFORCE mode requires ENFORCE maturity.","Advance policy maturity explicitly before enforcement.","UNMAPPED"});}
    for(const auto&b:c.ruleBindings){idCheck(b.id,"S6.DUPLICATE_BINDING");if(!knownAuthorities.contains(b.sourceAuthority))add(&result,{"S6.UNKNOWN_SOURCE_AUTHORITY","ERROR",b.sourceAuthority,b.sourceRuleCode,b.policyId,{}, {},"Rule binding references an unknown S authority.","Use S1 through S5 as the source authority.","UNMAPPED"});if(b.sourceRuleCode.isEmpty()||!validSeverity(b.minimumSeverity))add(&result,{"S6.INVALID_BINDING","ERROR",b.sourceAuthority,b.sourceRuleCode,b.policyId,{}, {},"Rule binding lacks a valid rule code or severity.","Provide stable source rule identity and severity.","UNMAPPED"});bool policy=false;for(const auto&p:c.enforcementPolicies)if(p.id==b.policyId)policy=true;if(!policy)add(&result,{"S6.UNKNOWN_POLICY","ERROR",b.sourceAuthority,b.sourceRuleCode,b.policyId,{}, {},"Rule binding references an unknown policy.","Declare the policy before binding a rule.","UNMAPPED"});for(const auto&t:b.enforcementTargets)if(!validTarget(t))add(&result,{"S6.INVALID_TARGET","ERROR",b.sourceAuthority,b.sourceRuleCode,b.policyId,{}, {},QStringLiteral("Unknown binding target: %1.").arg(t),"Use a canonical explicit enforcement target.","UNMAPPED"});}
    for(const auto&e:c.exemptions){idCheck(e.id,"S6.DUPLICATE_EXEMPTION");if(e.ruleCode.isEmpty()||e.reason.isEmpty()||e.approvedBy.isEmpty())add(&result,{"S6.INVALID_EXEMPTION","ERROR",{},e.ruleCode,{},e.scopeResponsibilityId,{},"Exemption requires rule, reason, and approval provenance.","Provide explicit governed approval metadata.","UNMAPPED"});if(!e.expiresAt.isEmpty()&&!QDateTime::fromString(e.expiresAt,Qt::ISODate).isValid())add(&result,{"S6.INVALID_EXEMPTION_EXPIRY","ERROR",{},e.ruleCode,{},e.scopeResponsibilityId,{},"Exemption expiry is not a valid ISO timestamp.","Use an explicit ISO timestamp.","UNMAPPED"});}
    for(const auto&w:c.waivers){idCheck(w.id,"S6.DUPLICATE_WAIVER");if(w.findingFingerprint.isEmpty()||w.reason.isEmpty()||w.approvedBy.isEmpty())add(&result,{"S6.INVALID_WAIVER","ERROR",{}, {},{}, {},{},"Waiver requires finding identity, reason, and approval provenance.","Provide a finding-specific governed waiver.","UNMAPPED"});if(!w.validUntil.isEmpty()&&!QDateTime::fromString(w.validUntil,Qt::ISODate).isValid())add(&result,{"S6.INVALID_WAIVER_EXPIRY","ERROR",{}, {},{}, {},{},"Waiver expiry is not a valid ISO timestamp.","Use an explicit ISO timestamp.","UNMAPPED"});}
    for(const auto&p:c.remediationPlans){idCheck(p.id,"S6.DUPLICATE_REMEDIATION");if(p.findingReferences.isEmpty()||p.proposedActions.isEmpty())add(&result,{"S6.INVALID_REMEDIATION","ERROR",{}, {},{}, {},{},"Remediation plan must retain findings and proposed actions.","Add stable finding references and inspectable actions.","UNMAPPED"});}
    for(const auto&p:c.migrationPlans){idCheck(p.id,"S6.DUPLICATE_MIGRATION");if(p.sourceStateFingerprint.isEmpty()||p.targetStateDescription.isEmpty())add(&result,{"S6.INVALID_MIGRATION","ERROR",{}, {},{}, {},{},"Migration plan requires source fingerprint and target state.","Describe the target and bind the source state.","UNMAPPED"});for(const auto&o:p.proposedOperations){if(!operations.contains(o.operation)||o.target.isEmpty())add(&result,{"S6.INVALID_OPERATION","ERROR",{}, {},p.id,{}, {},"Migration operation is unknown or has no exact target.","Use a canonical operation and exact target.","UNMAPPED"});if(o.destructive&&o.approvalState==ApprovalState::NotRequired)add(&result,{"S6.DESTRUCTIVE_WITHOUT_APPROVAL","BLOCKER",{}, {},p.id,{}, {},"Destructive migration operation lacks an approval requirement.","Require explicit governed approval and recovery metadata.","UNMAPPED"});}if((p.proposedOperations.size()>1||std::any_of(p.proposedOperations.begin(),p.proposedOperations.end(),[](const auto&o){return o.destructive;}))&&p.rollbackState==RollbackState::NotRequired)add(&result,{"S6.MISSING_ROLLBACK_DECLARATION","ERROR",{}, {},p.id,{}, {},"Multi-operation or destructive migration lacks rollback declaration.","Declare available, required, or explicitly unavailable recovery semantics.","UNMAPPED"});}
    std::sort(result.diagnostics.begin(),result.diagnostics.end(),[](const auto&a,const auto&b){return std::tie(a.ruleCode,a.sourceAuthority,a.sourceRuleCode,a.policyId,a.scopeResponsibilityId)<std::tie(b.ruleCode,b.sourceAuthority,b.sourceRuleCode,b.policyId,b.scopeResponsibilityId);});return result;
}

EnforcementDecision evaluate(const Finding& input, const Configuration& c, const QString& target, const QDateTime& now)
{
    Finding finding=input;finding.findingFingerprint=findingFingerprint(finding);EnforcementDecision d;d.findingAuthority=finding.sourceAuthority;d.findingRuleCode=finding.sourceRuleCode;d.findingFingerprint=finding.findingFingerprint;d.scopeResponsibilityId=finding.scopeResponsibilityId;d.enforcementTarget=target;d.evidenceReference=finding.evidenceReference;d.decisionId=hashObject({{"findingFingerprint",d.findingFingerprint},{"target",target},{"time",now.toUTC().toString(Qt::ISODate)}});
    if(!validTarget(target)||finding.sourceAuthority.isEmpty()||finding.sourceRuleCode.isEmpty()){d.reason="EVALUATION_ERROR: finding identity or target is incomplete.";return d;}
    const EnforcementPolicy* policy=nullptr;for(const auto&p:c.enforcementPolicies)if((p.scopeResponsibilityId.isEmpty()||p.scopeResponsibilityId==finding.scopeResponsibilityId)&&(!policy||(p.scopeResponsibilityId==finding.scopeResponsibilityId&&policy->scopeResponsibilityId.isEmpty())||(p.scopeResponsibilityId==policy->scopeResponsibilityId&&p.id<policy->id)))policy=&p;
    const RuleBinding* binding=nullptr;for(const auto&b:c.ruleBindings)if(b.sourceAuthority==finding.sourceAuthority&&b.sourceRuleCode==finding.sourceRuleCode&&(!binding||b.id<binding->id))binding=&b;
    d.policyId=policy?policy->id:QString();d.ruleBindingId=binding?binding->id:QString();d.mode=policy?policy->mode:Mode::Audit;d.disposition=binding?binding->disposition:(policy?policy->defaultDisposition:Disposition::Record);
    if(binding&&policy&&binding->policyId!=policy->id){d.reason="EVALUATION_ERROR: binding policy does not match selected policy.";return d;}
    const bool severityAllowed=!binding||severityRank(finding.severity)>=severityRank(binding->minimumSeverity);const bool targetAllowed=(!binding||binding->enforcementTargets.isEmpty()||binding->enforcementTargets.contains(target))&&( !policy||policy->enforcementTargets.isEmpty()||policy->enforcementTargets.contains(target));
    for(const auto&w:c.waivers)if(w.findingFingerprint==finding.findingFingerprint&&w.status=="ACTIVE"&&w.approvedBy.size()&&!w.validUntil.isEmpty()&&QDateTime::fromString(w.validUntil,Qt::ISODate)>=now){d.waiverId=w.id;d.disposition=Disposition::Ignore;d.reason="Finding-specific waiver applies.";return d;}
    for(const auto&e:c.exemptions)if(e.status=="ACTIVE"&&e.approvedBy.size()&&e.reason.size()&&e.ruleCode==finding.sourceRuleCode&&(e.scopeResponsibilityId.isEmpty()||e.scopeResponsibilityId==finding.scopeResponsibilityId)&&(!e.expiresAt.isEmpty()&&QDateTime::fromString(e.expiresAt,Qt::ISODate)>=now)){d.exemptionId=e.id;d.disposition=Disposition::Ignore;d.reason="Scoped exemption applies.";return d;}
    if(!severityAllowed||!targetAllowed){d.reason="Finding is outside the configured binding threshold or target.";return d;}
    if(d.mode==Mode::Enforce&&policy&&policy->maturity==Maturity::Enforce&&d.disposition==Disposition::Block){d.blocked=true;d.reason=QStringLiteral("Blocked by S6 policy %1 for %2/%3 at %4.").arg(d.policyId,finding.sourceAuthority,finding.sourceRuleCode,target);}else if(d.mode==Mode::Warn||d.disposition==Disposition::Warn||d.disposition==Disposition::RequireAcknowledgement){d.reason="Governed warning; no hard block is applied.";}else d.reason="Recorded under the safe non-blocking default.";return d;
}

RemediationPlan planRemediation(const Finding& finding, const QStringList& actions, const QString& stableId)
{ RemediationPlan p;p.id=stableId.isEmpty()?stable(findingFingerprint(finding),"remediation"):stableId;p.stableKey=p.id;p.findingReferences={findingFingerprint(finding)};p.proposedActions=actions;p.requiresApproval=true;return p; }
MigrationPlan planMigration(const QString& source, const QString& targetState, const QStringList& responsibilities, const QStringList& artifacts, const QList<MigrationOperation>& operationsList, const QString& stableId)
{ MigrationPlan p;p.id=stableId.isEmpty()?stable(source+targetState,"migration"):stableId;p.stableKey=p.id;p.sourceStateFingerprint=source;p.targetStateDescription=targetState;p.affectedResponsibilities=responsibilities;p.affectedArtifacts=artifacts;p.proposedOperations=operationsList;p.approvalState=ApprovalState::Required;p.rollbackState=operationsList.size()>1?RollbackState::Required:RollbackState::Available;return p; }
DryRunResult dryRunMigration(const MigrationPlan& plan)
{ DryRunResult r;r.expectedTargetState=plan.targetStateDescription;r.affectedArtifacts=plan.affectedArtifacts;for(const auto&o:plan.proposedOperations){r.operations.append(o.operation+QStringLiteral(":")+o.target);}std::sort(r.operations.begin(),r.operations.end());r.planFingerprint=hashObject(migrationJson(plan));r.reason="DRY_RUN only: no project artifact was modified.";return r; }

QJsonObject AuditResult::toJson() const { QJsonArray a;for(const auto&d:diagnostics)a.append(QJsonObject{{"ruleCode",d.ruleCode},{"severity",d.severity},{"sourceAuthority",d.sourceAuthority},{"sourceRuleCode",d.sourceRuleCode},{"policyId",d.policyId},{"ruleBindingId",d.ruleBindingId},{"scopeResponsibilityId",d.scopeResponsibilityId},{"reason",d.reason},{"requiredAction",d.requiredAction},{"migrationStatus",d.migrationStatus}});return {{"valid",valid},{"modelFingerprint",modelFingerprint},{"diagnostics",a}}; }
QJsonObject DryRunResult::toJson() const { return {{"valid",valid},{"planFingerprint",planFingerprint},{"expectedTargetState",expectedTargetState},{"affectedArtifacts",strings(affectedArtifacts)},{"operations",strings(operations)},{"reason",reason}}; }
} // namespace S6
